install:
  - curl -LO https://github.com/gohugoio/hugo/releases/download/v0.62.0/hugo_0.62.0_Linux-64bit.deb
  - sudo dpkg -i hugo_0.62.0_Linux-64bit.deb
script:
  - hugo
  - cp layouts/404.html public/
deploy:
  target-branch: gh-pages
  github_token: "$GITHUB_TOKEN"
  skip-cleanup: true
  local-dir: "./public/"
  provider: pages
  on:
    branch: master
