name: Hugo CI

on: [push, pull_request]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Install Hugo
      env:
        HUGO_VERSION: "0.99.1"
      run: |
        curl -LO https://github.com/gohugoio/hugo/releases/download/v${HUGO_VERSION}/hugo_extended_${HUGO_VERSION}_Linux-64bit.deb
        sudo dpkg -i hugo_extended_${HUGO_VERSION}_Linux-64bit.deb
    - name: Generate website
      run: |
        hugo
        cp layouts/404.html public/
    - name: Deploy
      if: github.ref == 'refs/heads/master' && github.event_name == 'push'
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./public/
